import {
  faGithub,
  faLinkedin,
  faLinkedinIn,
  faTwitter,
  faTwitterSquare,
} from "@fortawesome/free-brands-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Sean Barker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-3xl mx-auto py-4 px-4 sm:py-6 sm:px-12 lg:px-8">
        <section>
          <h2 className="text-3xl font-extrabold text-slate-50 sm:text-4xl tracking-tight mb-12">
            <span className="block leading-12">Hey there 👋</span>
            <span className="block underline underline-offset-2 decoration-8 decoration-rose-600 text-slate-60 leading-12">
              I'm Sean Barker.
            </span>
          </h2>
          <div className="bg-slate-800 rounded-lg mt-8 mb-4 shadow-xl shadow-slate-800/50">
            <div className="flex items-center space-x-2 border-b border-b-slate-400 p-4">
              <div className="h-3 w-3 bg-rose-600 rounded-full" />
              <div className="h-3 w-3 bg-yellow-400 rounded-full" />
              <div className="h-3 w-3 bg-green-500 rounded-full" />
            </div>
            <div className="p-4">
              <Code selfClose={false} lnNum={1}>
                Me
              </Code>
              <Code lnNum={2} indent={1}>
                👨‍👩‍👧Dad
              </Code>
              <Code lnNum={3} indent={1}>
                👨‍💻Developer
              </Code>
              <Code lnNum={4} indent={1}>
                💻TechEnthusiast
              </Code>
              <Code selfClose={false} closingTag={true} lnNum={5}>
                Me
              </Code>
            </div>
          </div>
        </section>
        <article className="mt-12">
          <p className="text-white text-lg">
            I'm a full stack developer at Reusser in Roanoke, Indiana. My
            favorite technologies to use at the moment are React, Node,
            Typescript, Framer Motion, and React Native. I'm currently playing
            around with Swift and Tensorflow.js, and hope to eventually learn
            SvelteKit and Go.
          </p>
          <p className="text-white text-lg mt-6">
            I'm not searching for new opportunities at the moment, but would
            love to connect with you on one of the sites below.
          </p>
        </article>
      </main>
      <footer className="mt-16">
        <div className="max-w-3xl mx-auto px-4 sm:px-12 lg:px-8 py-4">
          <div className="flex flex-col sm:flex-row justify-between">
            <ul className="flex space-x-4">
              <li>
                <a
                  href="https://www.linkedin.com/in/sean-barker/"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <span className="sr-only">LinkedIn</span>
                  <FontAwesomeIcon
                    icon={faLinkedinIn}
                    className="w-8 text-slate-50 text-opacity-50 hover:text-opacity-100"
                  />
                </a>
              </li>
              <li>
                <a href="https://twitter.com/seanbarkerdev" target="_blank">
                  <span className="sr-only">Twitter</span>
                  <FontAwesomeIcon
                    icon={faTwitter}
                    className="w-9 text-slate-50 text-opacity-50 hover:text-opacity-100"
                  />
                </a>
              </li>
              <li>
                <a href="https://github.com/seanbarker182" target="_blank">
                  <span className="sr-only">GitHub</span>
                  <FontAwesomeIcon
                    icon={faGithub}
                    className="w-8 text-slate-50 text-opacity-50 hover:text-opacity-100"
                  />
                </a>
              </li>
            </ul>
            <p className="text-slate-50 text-opacity-50 text-sm leading-none mb-1 mt-2 sm:mt-auto">
              © Sean Barker {new Date().getFullYear()}. All rights reserved.
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
};

const Code: React.FC<{
  children: string;
  selfClose?: boolean;
  closingTag?: boolean;
  lnNum: number;
  indent?: number;
}> = ({
  lnNum = 1,
  indent = 0,
  selfClose = true,
  closingTag = false,
  children,
}) => (
  <code className="flex items-center font-mono text-lg text-yellow-400">
    <div className="mr-4 text-sm text-slate-400">{lnNum}</div>
    <span className="text-gray-50 text-xl" style={{ marginLeft: indent * 16 }}>
      {closingTag ? "</" : "<"}
    </span>
    {children}&nbsp;
    <span className="text-slate-50 text-xl">{selfClose ? "/>" : ">"}</span>
  </code>
);

export default Home;
